"""Add time field

Revision ID: 10f90bcb56aa
Revises: 808e3e562075
Create Date: 2022-06-27 00:30:37.122243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10f90bcb56aa'
down_revision = '808e3e562075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nifty_day_data', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('nifty_day_data', sa.Column('time', sa.Time(), nullable=True))
    op.drop_index('ix_nifty_day_data_datetime', table_name='nifty_day_data')
    op.create_index(op.f('ix_nifty_day_data_date'), 'nifty_day_data', ['date'], unique=True)
    op.create_index(op.f('ix_nifty_day_data_time'), 'nifty_day_data', ['time'], unique=False)
    op.drop_column('nifty_day_data', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nifty_day_data', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_nifty_day_data_time'), table_name='nifty_day_data')
    op.drop_index(op.f('ix_nifty_day_data_date'), table_name='nifty_day_data')
    op.create_index('ix_nifty_day_data_datetime', 'nifty_day_data', ['datetime'], unique=False)
    op.drop_column('nifty_day_data', 'time')
    op.drop_column('nifty_day_data', 'date')
    # ### end Alembic commands ###
