"""Fix unique constraint

Revision ID: 3cf254ecba6f
Revises: f1c0210f5148
Create Date: 2022-06-27 13:22:38.233817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf254ecba6f'
down_revision = 'f1c0210f5148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_date_time', 'nifty_day_data', type_='unique')
    op.create_unique_constraint('unique_date_time', 'nifty_day_data', ['ticker_date', 'ticker_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_date_time', 'nifty_day_data', type_='unique')
    op.create_unique_constraint('unique_date_time', 'nifty_day_data', ['ticker_date'])
    # ### end Alembic commands ###
