"""create holiday table

Revision ID: 41dba14dda03
Revises: 540e172ff3be
Create Date: 2022-04-26 00:26:49.545841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dba14dda03'
down_revision = '540e172ff3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holiday_holiday_date'), 'holiday', ['holiday_date'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holiday_holiday_date'), table_name='holiday')
    op.drop_table('holiday')
    # ### end Alembic commands ###
