"""create tables

Revision ID: 540e172ff3be
Revises: 
Create Date: 2022-04-25 23:10:25.599175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540e172ff3be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_index',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_index_name'), 'stock_index', ['name'], unique=True)
    op.create_table('option_strike',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('stock_index_id', sa.BigInteger(), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('strike', sa.Integer(), nullable=True),
    sa.Column('option_type', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['stock_index_id'], ['stock_index.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_option_strike_expiry'), 'option_strike', ['expiry'], unique=False)
    op.create_index(op.f('ix_option_strike_option_type'), 'option_strike', ['option_type'], unique=False)
    op.create_index(op.f('ix_option_strike_strike'), 'option_strike', ['strike'], unique=False)
    op.create_table('historical_price',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(precision=2), nullable=True),
    sa.Column('high', sa.Float(precision=2), nullable=True),
    sa.Column('low', sa.Float(precision=2), nullable=True),
    sa.Column('close', sa.Float(precision=2), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('oi', sa.Integer(), nullable=True),
    sa.Column('ticker_datetime', sa.DateTime(), nullable=True),
    sa.Column('option_strike_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['option_strike_id'], ['option_strike.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_price_ticker_datetime'), 'historical_price', ['ticker_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_price_ticker_datetime'), table_name='historical_price')
    op.drop_table('historical_price')
    op.drop_index(op.f('ix_option_strike_strike'), table_name='option_strike')
    op.drop_index(op.f('ix_option_strike_option_type'), table_name='option_strike')
    op.drop_index(op.f('ix_option_strike_expiry'), table_name='option_strike')
    op.drop_table('option_strike')
    op.drop_index(op.f('ix_stock_index_name'), table_name='stock_index')
    op.drop_table('stock_index')
    # ### end Alembic commands ###
