"""Remove standalone unique constraint from date

Revision ID: 89e5a0dc22d1
Revises: 30741c7ee2ed
Create Date: 2022-06-27 12:56:44.250191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e5a0dc22d1'
down_revision = '30741c7ee2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nifty_day_data_date', table_name='nifty_day_data')
    op.create_index(op.f('ix_nifty_day_data_date'), 'nifty_day_data', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nifty_day_data_date'), table_name='nifty_day_data')
    op.create_index('ix_nifty_day_data_date', 'nifty_day_data', ['date'], unique=False)
    # ### end Alembic commands ###
