"""nifty day data table

Revision ID: 994e278b4b12
Revises: a4ffbcfad69c
Create Date: 2022-05-19 16:29:24.511191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994e278b4b12'
down_revision = 'a4ffbcfad69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nifty_day_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('open', sa.Float(precision=2), nullable=True),
    sa.Column('high', sa.Float(precision=2), nullable=True),
    sa.Column('low', sa.Float(precision=2), nullable=True),
    sa.Column('close', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nifty_day_data_date'), 'nifty_day_data', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nifty_day_data_date'), table_name='nifty_day_data')
    op.drop_table('nifty_day_data')
    # ### end Alembic commands ###
