"""add unique constraint name

Revision ID: a4ffbcfad69c
Revises: ecb62a320f39
Create Date: 2022-04-26 21:26:49.651063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ffbcfad69c'
down_revision = 'ecb62a320f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('historical_price_option_strike_id_ticker_datetime_key', 'historical_price', type_='unique')
    op.create_unique_constraint('unique_strike_dt', 'historical_price', ['option_strike_id', 'ticker_datetime'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_strike_dt', 'historical_price', type_='unique')
    op.create_unique_constraint('historical_price_option_strike_id_ticker_datetime_key', 'historical_price', ['option_strike_id', 'ticker_datetime'])
    # ### end Alembic commands ###
