"""Add table for nifty 50 minute data

Revision ID: d4832f634f5e
Revises: 3cf254ecba6f
Create Date: 2022-06-27 13:49:43.567374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4832f634f5e'
down_revision = '3cf254ecba6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nifty_minute_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker_date', sa.Date(), nullable=True),
    sa.Column('ticker_time', sa.Time(), nullable=True),
    sa.Column('open', sa.Float(precision=2), nullable=True),
    sa.Column('high', sa.Float(precision=2), nullable=True),
    sa.Column('low', sa.Float(precision=2), nullable=True),
    sa.Column('close', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_date', 'ticker_time', name='unique_date_time_nifty_minute_data')
    )
    op.create_index(op.f('ix_nifty_minute_data_ticker_date'), 'nifty_minute_data', ['ticker_date'], unique=False)
    op.create_index(op.f('ix_nifty_minute_data_ticker_time'), 'nifty_minute_data', ['ticker_time'], unique=False)
    op.drop_index('ix_nifty_day_data_ticker_time', table_name='nifty_day_data')
    op.drop_constraint('unique_date_time', 'nifty_day_data', type_='unique')
    op.drop_index('ix_nifty_day_data_ticker_date', table_name='nifty_day_data')
    op.create_index(op.f('ix_nifty_day_data_ticker_date'), 'nifty_day_data', ['ticker_date'], unique=True)
    op.drop_column('nifty_day_data', 'ticker_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nifty_day_data', sa.Column('ticker_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_nifty_day_data_ticker_date'), table_name='nifty_day_data')
    op.create_index('ix_nifty_day_data_ticker_date', 'nifty_day_data', ['ticker_date'], unique=False)
    op.create_unique_constraint('unique_date_time', 'nifty_day_data', ['ticker_date', 'ticker_time'])
    op.create_index('ix_nifty_day_data_ticker_time', 'nifty_day_data', ['ticker_time'], unique=False)
    op.drop_index(op.f('ix_nifty_minute_data_ticker_time'), table_name='nifty_minute_data')
    op.drop_index(op.f('ix_nifty_minute_data_ticker_date'), table_name='nifty_minute_data')
    op.drop_table('nifty_minute_data')
    # ### end Alembic commands ###
