"""Rename date time field

Revision ID: f1c0210f5148
Revises: 89e5a0dc22d1
Create Date: 2022-06-27 13:20:25.726272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1c0210f5148'
down_revision = '89e5a0dc22d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nifty_day_data', sa.Column('ticker_date', sa.Date(), nullable=True))
    op.add_column('nifty_day_data', sa.Column('ticker_time', sa.Time(), nullable=True))
    op.drop_index('ix_nifty_day_data_date', table_name='nifty_day_data')
    op.drop_index('ix_nifty_day_data_time', table_name='nifty_day_data')
    op.drop_constraint('unique_date_time', 'nifty_day_data', type_='unique')
    op.create_unique_constraint('unique_date_time', 'nifty_day_data', ['ticker_date'])
    op.create_index(op.f('ix_nifty_day_data_ticker_date'), 'nifty_day_data', ['ticker_date'], unique=False)
    op.create_index(op.f('ix_nifty_day_data_ticker_time'), 'nifty_day_data', ['ticker_time'], unique=False)
    op.drop_column('nifty_day_data', 'time')
    op.drop_column('nifty_day_data', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nifty_day_data', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('nifty_day_data', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_nifty_day_data_ticker_time'), table_name='nifty_day_data')
    op.drop_index(op.f('ix_nifty_day_data_ticker_date'), table_name='nifty_day_data')
    op.drop_constraint('unique_date_time', 'nifty_day_data', type_='unique')
    op.create_unique_constraint('unique_date_time', 'nifty_day_data', ['date', 'time'])
    op.create_index('ix_nifty_day_data_time', 'nifty_day_data', ['time'], unique=False)
    op.create_index('ix_nifty_day_data_date', 'nifty_day_data', ['date'], unique=False)
    op.drop_column('nifty_day_data', 'ticker_time')
    op.drop_column('nifty_day_data', 'ticker_date')
    # ### end Alembic commands ###
